# Generated by Django 5.2.7 on 2025-10-06 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=20)),
                ('building', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('full_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('individual', 'Физическое лицо'), ('company', 'Юридическое лицо')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=200)),
                ('equipment_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('power', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электричество'), ('hybrid', 'Гибрид'), ('gas', 'Газ'), ('other', 'Другое')], default='petrol', max_length=20)),
                ('rental_price_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('rented', 'В аренде'), ('maintenance', 'На обслуживании')], default='available', max_length=20)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental_system.equipmentbrands')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental_system.equipmentcountries')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental_system.equipmentmodels')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental_system.role')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_agreement_number', models.CharField(max_length=50)),
                ('rent_agreement_date', models.DateField()),
                ('start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('rent_status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершен'), ('extended', 'Продлен')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], max_length=20, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.client')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'Проводится'), ('completed', 'Завершено')], default='planned', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.equipment')),
                ('work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental_system.maintenancetype')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental_system.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('LOGIN', 'Вход в систему'), ('LOGOUT', 'Выход из системы'), ('CREATE', 'Создание объекта'), ('UPDATE', 'Обновление объекта'), ('DELETE', 'Удаление объекта'), ('VIEW', 'Просмотр объекта'), ('EXPORT', 'Экспорт данных'), ('IMPORT', 'Импорт данных'), ('ASSIGN', 'Назначение/переназначение'), ('CHANGE_STATUS', 'Изменение статуса'), ('UPLOAD', 'Загрузка файла'), ('DOWNLOAD', 'Скачивание файла'), ('LOGIN_FAILED', 'Неудачная попытка входа'), ('PERMISSION_CHANGE', 'Изменение прав доступа'), ('OTHER', 'Другое действие')], default='OTHER', max_length=100)),
                ('success_status', models.BooleanField(default=True)),
                ('description_text', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental_system.staff')),
            ],
        ),
        migrations.CreateModel(
            name='CompClient',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rental_system.client')),
                ('company_name', models.CharField(max_length=200)),
                ('inn', models.CharField(max_length=20)),
                ('kpp', models.CharField(max_length=20)),
                ('ogrn', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_bik', models.CharField(max_length=20)),
                ('bank_account', models.CharField(max_length=50)),
                ('bank_corr', models.CharField(max_length=50)),
                ('director_first_name', models.CharField(max_length=100)),
                ('director_last_name', models.CharField(max_length=100)),
                ('director_patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(max_length=100)),
                ('attorney_number', models.CharField(blank=True, max_length=50, null=True)),
                ('attorney_date', models.DateField(blank=True, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental_system.address')),
            ],
        ),
        migrations.CreateModel(
            name='IndClient',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rental_system.client')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('passport_issued_by', models.CharField(max_length=200)),
                ('passport_issued_date', models.DateField()),
                ('passport_code', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('inn', models.CharField(blank=True, max_length=20, null=True)),
                ('actual_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_clients', to='rental_system.address')),
                ('registration_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_clients', to='rental_system.address')),
            ],
        ),
        migrations.CreateModel(
            name='RentItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.equipment')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.rent')),
            ],
            options={
                'unique_together': {('rent', 'equipment')},
            },
        ),
    ]
