# Generated by Django 5.2.7 on 2025-11-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0005_use_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_code',
            field=models.CharField(help_text='Уникальный номер оборудования', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(help_text='Название крупногабаритной машины', max_length=200),
        ),
    ]
