# Generated by Django 5.2.7 on 2025-11-23
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental_system", "0006_alter_equipment_equipment_code_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION log_table_changes()
            RETURNS TRIGGER AS $$
            DECLARE
                v_action_type TEXT;
                v_description TEXT;
                v_old_data JSONB;
                v_new_data JSONB;
                v_changed_fields TEXT[];
                v_field TEXT;
            BEGIN
                IF TG_OP = 'INSERT' THEN
                    v_action_type := 'CREATE';
                    v_new_data := to_jsonb(NEW);
                    v_description := CONCAT(
                        'Создан новый объект в таблице ', TG_TABLE_NAME,
                        '. Данные: ', v_new_data::TEXT
                    );

                ELSIF TG_OP = 'UPDATE' THEN
                    v_action_type := 'UPDATE';
                    v_old_data := to_jsonb(OLD);
                    v_new_data := to_jsonb(NEW);

                    v_changed_fields := ARRAY[]::TEXT[];
                    FOR v_field IN SELECT jsonb_object_keys(v_old_data) LOOP
                        IF v_old_data->>v_field IS DISTINCT FROM v_new_data->>v_field THEN
                            v_changed_fields := array_append(
                                v_changed_fields,
                                CONCAT(
                                    v_field, ': ',
                                    COALESCE(v_old_data->>v_field, 'NULL'),
                                    ' → ',
                                    COALESCE(v_new_data->>v_field, 'NULL')
                                )
                            );
                        END IF;
                    END LOOP;

                    v_description := CONCAT(
                        'Обновлен объект в таблице ', TG_TABLE_NAME,
                        '. ID: ', COALESCE(OLD.id::TEXT, NEW.id::TEXT),
                        '. Измененные поля: ', array_to_string(v_changed_fields, '; ')
                    );

                ELSIF TG_OP = 'DELETE' THEN
                    v_action_type := 'DELETE';
                    v_old_data := to_jsonb(OLD);
                    v_description := CONCAT(
                        'Удален объект из таблицы ', TG_TABLE_NAME,
                        '. ID: ', OLD.id::TEXT,
                        '. Данные: ', v_old_data::TEXT
                    );
                END IF;

                INSERT INTO rental_system_log(
                    log_date,
                    action_type,
                    description_text,
                    success_status
                ) VALUES (
                    CURRENT_TIMESTAMP,
                    v_action_type,
                    v_description,
                    TRUE
                );

                RETURN CASE
                    WHEN TG_OP = 'DELETE' THEN OLD
                    ELSE NEW
                END;
            END;
            $$ LANGUAGE plpgsql;
            """,
            """
            DROP FUNCTION IF EXISTS log_table_changes CASCADE;
            """,
        ),
    ]

