# Generated by Django 5.2.7 on 2025-11-23
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental_system", "0011_fix_log_table_changes"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Удаляем старый триггер и функцию с опечаткой
            DROP TRIGGER IF EXISTS set_equipment_rented ON rental_system_rentitems;
            DROP FUNCTION IF EXISTS set_equipment_rented() CASCADE;

            -- Создаем корректную функцию
            CREATE OR REPLACE FUNCTION set_equipment_rented()
            RETURNS TRIGGER AS $$
            BEGIN
                UPDATE rental_system_equipment
                SET status = 'rented'
                WHERE id = NEW.equipment_id;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- Создаем триггер заново
            CREATE TRIGGER set_equipment_rented
            AFTER INSERT ON rental_system_rentitems
            FOR EACH ROW EXECUTE FUNCTION set_equipment_rented();
            """,
            """
            DROP TRIGGER IF EXISTS set_equipment_rented ON rental_system_rentitems;
            DROP FUNCTION IF EXISTS set_equipment_rented() CASCADE;
            """,
        )
    ]

