# Generated by Django 5.2.7 on 2025-11-23
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental_system", "0012_fix_set_equipment_rented"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Обновляем функцию логирования смены статусов, чтобы писать log_date
            CREATE OR REPLACE FUNCTION log_status_changes()
            RETURNS TRIGGER AS $$
            BEGIN
                IF TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status THEN
                    INSERT INTO rental_system_log(
                        log_date,
                        action_type,
                        description_text,
                        success_status
                    ) VALUES (
                        CURRENT_TIMESTAMP,
                        'CHANGE_STATUS',
                        CONCAT(
                            'Изменен статус в таблице ', TG_TABLE_NAME,
                            '. ID: ', OLD.id::TEXT,
                            '. Статус: ', COALESCE(OLD.status::TEXT, 'NULL'),
                            ' → ', COALESCE(NEW.status::TEXT, 'NULL')
                        ),
                        TRUE
                    );
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            """
            DROP FUNCTION IF EXISTS log_status_changes() CASCADE;
            """,
        ),
    ]

