# Generated by Django 5.2.7 on 2025-11-23
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental_system", "0013_fix_log_status_changes"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Устанавливаем дефолт для log_date, чтобы избежать NULL
            ALTER TABLE rental_system_log
            ALTER COLUMN log_date SET DEFAULT CURRENT_TIMESTAMP;
            """,
            """
            ALTER TABLE rental_system_log
            ALTER COLUMN log_date DROP DEFAULT;
            """,
        ),
        migrations.RunSQL(
            """
            -- Обновляем функцию логирования назначений
            CREATE OR REPLACE FUNCTION log_assignments()
            RETURNS TRIGGER AS $$
            BEGIN
                IF TG_OP = 'UPDATE' AND OLD.staff_id IS DISTINCT FROM NEW.staff_id THEN
                    INSERT INTO rental_system_log(
                        log_date,
                        action_type,
                        description_text,
                        success_status
                    ) VALUES (
                        CURRENT_TIMESTAMP,
                        'ASSIGN',
                        CONCAT(
                            'Изменено назначение в таблице ', TG_TABLE_NAME,
                            '. ID: ', OLD.id::TEXT,
                            '. Сотрудник: ', COALESCE(OLD.staff_id::TEXT, 'NULL'),
                            ' → ', COALESCE(NEW.staff_id::TEXT, 'NULL')
                        ),
                        TRUE
                    );
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            """
            DROP FUNCTION IF EXISTS log_assignments() CASCADE;
            """,
        ),
        migrations.RunSQL(
            """
            -- Обновляем функцию логирования событий аутентификации
            CREATE OR REPLACE FUNCTION log_auth_events()
            RETURNS TRIGGER AS $$
            DECLARE
                v_action_type TEXT;
                v_description TEXT;
            BEGIN
                IF TG_OP = 'INSERT' THEN
                    v_action_type := UPPER(NEW.event_type);
                    v_description := CONCAT(
                        'Событие аутентификации: ', NEW.event_type,
                        '. Пользователь: ', COALESCE(NEW.username, 'Unknown'),
                        '. IP: ', COALESCE(NEW.ip_address, 'Unknown'),
                        '. Успех: ', NEW.success
                    );

                    IF NEW.event_type = 'login' AND NEW.success THEN
                        v_action_type := 'LOGIN';
                    ELSIF NEW.event_type = 'login' AND NOT NEW.success THEN
                        v_action_type := 'LOGIN_FAILED';
                    ELSIF NEW.event_type = 'logout' THEN
                        v_action_type := 'LOGOUT';
                    END IF;
                END IF;

                INSERT INTO rental_system_log(
                    log_date,
                    staff_id,
                    action_type,
                    description_text,
                    success_status
                ) VALUES (
                    CURRENT_TIMESTAMP,
                    (SELECT id FROM rental_system_staff WHERE login = NEW.username LIMIT 1),
                    v_action_type,
                    v_description,
                    NEW.success
                );

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            """
            DROP FUNCTION IF EXISTS log_auth_events() CASCADE;
            """,
        ),
        migrations.RunSQL(
            """
            -- Обновляем вспомогательные функции логирования, чтобы писать log_date
            CREATE OR REPLACE FUNCTION log_custom_action(
                p_staff_id INT,
                p_action_type TEXT,
                p_description TEXT,
                p_success BOOLEAN DEFAULT TRUE
            )
            RETURNS VOID AS $$
            BEGIN
                INSERT INTO rental_system_log(
                    log_date,
                    staff_id,
                    action_type,
                    description_text,
                    success_status
                ) VALUES (
                    CURRENT_TIMESTAMP,
                    p_staff_id,
                    p_action_type,
                    p_description,
                    p_success
                );
            END;
            $$ LANGUAGE plpgsql;
            """,
            """
            DROP FUNCTION IF EXISTS log_custom_action(INT, TEXT, TEXT, BOOLEAN);
            """,
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION log_file_operation(
                p_staff_id INT,
                p_action_type TEXT,
                p_filename TEXT,
                p_success BOOLEAN DEFAULT TRUE
            )
            RETURNS VOID AS $$
            BEGIN
                INSERT INTO rental_system_log(
                    log_date,
                    staff_id,
                    action_type,
                    description_text,
                    success_status
                ) VALUES (
                    CURRENT_TIMESTAMP,
                    p_staff_id,
                    p_action_type,
                    CONCAT('Файл: ', p_filename, '. Действие: ', p_action_type),
                    p_success
                );
            END;
            $$ LANGUAGE plpgsql;
            """,
            """
            DROP FUNCTION IF EXISTS log_file_operation(INT, TEXT, TEXT, BOOLEAN);
            """,
        ),
    ]

