# Generated by Django 5.2.7 on 2025-11-23
from django.db import migrations


LOG_USER_EXPR = "NULLIF(current_setting('application.user_id', true), '')::INT"


class Migration(migrations.Migration):
    dependencies = [
        ("rental_system", "0014_fix_log_defaults"),
    ]

    operations = [
        migrations.RunSQL(
            f"""
            CREATE OR REPLACE FUNCTION log_table_changes()
            RETURNS TRIGGER AS $$
            DECLARE
                v_action_type TEXT;
                v_description TEXT;
                v_old_data JSONB;
                v_new_data JSONB;
                v_changed_fields TEXT[];
                v_field TEXT;
                v_staff_id INT := {LOG_USER_EXPR};
            BEGIN
                IF TG_OP = 'INSERT' THEN
                    v_action_type := 'CREATE';
                    v_new_data := to_jsonb(NEW);
                    v_description := CONCAT('Создан новый объект в таблице ', TG_TABLE_NAME, '. Данные: ', v_new_data::TEXT);
                ELSIF TG_OP = 'UPDATE' THEN
                    v_action_type := 'UPDATE';
                    v_old_data := to_jsonb(OLD);
                    v_new_data := to_jsonb(NEW);
                    v_changed_fields := ARRAY[]::TEXT[];
                    FOR v_field IN SELECT jsonb_object_keys(v_old_data) LOOP
                        IF v_old_data->>v_field IS DISTINCT FROM v_new_data->>v_field THEN
                            v_changed_fields := array_append(v_changed_fields,
                                CONCAT(v_field, ': ', COALESCE(v_old_data->>v_field, 'NULL'), ' → ', COALESCE(v_new_data->>v_field, 'NULL'))
                            );
                        END IF;
                    END LOOP;
                    v_description := CONCAT('Обновлен объект в таблице ', TG_TABLE_NAME, '. ID: ', COALESCE(OLD.id::TEXT, NEW.id::TEXT), '. Измененные поля: ', array_to_string(v_changed_fields, '; '));
                ELSIF TG_OP = 'DELETE' THEN
                    v_action_type := 'DELETE';
                    v_old_data := to_jsonb(OLD);
                    v_description := CONCAT('Удален объект из таблицы ', TG_TABLE_NAME, '. ID: ', OLD.id::TEXT, '. Данные: ', v_old_data::TEXT);
                END IF;

                INSERT INTO rental_system_log(
                    log_date,
                    staff_id,
                    action_type,
                    description_text,
                    success_status
                ) VALUES (
                    CURRENT_TIMESTAMP,
                    v_staff_id,
                    v_action_type,
                    v_description,
                    TRUE
                );

                RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS log_table_changes() CASCADE;",
        ),
        migrations.RunSQL(
            f"""
            CREATE OR REPLACE FUNCTION log_status_changes()
            RETURNS TRIGGER AS $$
            DECLARE
                v_staff_id INT := {LOG_USER_EXPR};
            BEGIN
                IF TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status THEN
                    INSERT INTO rental_system_log(
                        log_date,
                        staff_id,
                        action_type,
                        description_text,
                        success_status
                    ) VALUES (
                        CURRENT_TIMESTAMP,
                        v_staff_id,
                        'CHANGE_STATUS',
                        CONCAT('Изменен статус в таблице ', TG_TABLE_NAME, '. ID: ', OLD.id::TEXT, '. Статус: ', COALESCE(OLD.status::TEXT, 'NULL'), ' → ', COALESCE(NEW.status::TEXT, 'NULL')),
                        TRUE
                    );
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS log_status_changes() CASCADE;",
        ),
        migrations.RunSQL(
            f"""
            CREATE OR REPLACE FUNCTION log_assignments()
            RETURNS TRIGGER AS $$
            DECLARE
                v_staff_id INT := {LOG_USER_EXPR};
            BEGIN
                IF TG_OP = 'UPDATE' AND OLD.staff_id IS DISTINCT FROM NEW.staff_id THEN
                    INSERT INTO rental_system_log(
                        log_date,
                        staff_id,
                        action_type,
                        description_text,
                        success_status
                    ) VALUES (
                        CURRENT_TIMESTAMP,
                        v_staff_id,
                        'ASSIGN',
                        CONCAT('Изменено назначение в таблице ', TG_TABLE_NAME, '. ID: ', OLD.id::TEXT, '. Сотрудник: ', COALESCE(OLD.staff_id::TEXT, 'NULL'), ' → ', COALESCE(NEW.staff_id::TEXT, 'NULL')),
                        TRUE
                    );
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS log_assignments() CASCADE;",
        ),
        migrations.RunSQL(
            f"""
            CREATE OR REPLACE FUNCTION log_custom_action(
                p_staff_id INT,
                p_action_type TEXT,
                p_description TEXT,
                p_success BOOLEAN DEFAULT TRUE
            )
            RETURNS VOID AS $$
            DECLARE
                v_staff_id INT := COALESCE(p_staff_id, {LOG_USER_EXPR});
            BEGIN
                INSERT INTO rental_system_log(
                    log_date,
                    staff_id,
                    action_type,
                    description_text,
                    success_status
                ) VALUES (
                    CURRENT_TIMESTAMP,
                    v_staff_id,
                    p_action_type,
                    p_description,
                    p_success
                );
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS log_custom_action(INT, TEXT, TEXT, BOOLEAN);",
        ),
        migrations.RunSQL(
            f"""
            CREATE OR REPLACE FUNCTION log_file_operation(
                p_staff_id INT,
                p_action_type TEXT,
                p_filename TEXT,
                p_success BOOLEAN DEFAULT TRUE
            )
            RETURNS VOID AS $$
            DECLARE
                v_staff_id INT := COALESCE(p_staff_id, {LOG_USER_EXPR});
            BEGIN
                INSERT INTO rental_system_log(
                    log_date,
                    staff_id,
                    action_type,
                    description_text,
                    success_status
                ) VALUES (
                    CURRENT_TIMESTAMP,
                    v_staff_id,
                    p_action_type,
                    CONCAT('Файл: ', p_filename, '. Действие: ', p_action_type),
                    p_success
                );
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS log_file_operation(INT, TEXT, TEXT, BOOLEAN);",
        ),
    ]

