# Generated by Django 5.2.7 on 2025-11-23
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rental_system", "0015_log_functions_use_session_user"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Обновляем триггеры, чтобы точно указывать актуальные функции логирования
            DROP TRIGGER IF EXISTS log_equipment_changes ON rental_system_equipment;
            DROP TRIGGER IF EXISTS log_client_changes ON rental_system_client;
            DROP TRIGGER IF EXISTS log_rent_changes ON rental_system_rent;
            DROP TRIGGER IF EXISTS log_equipment_status_changes ON rental_system_equipment;
            DROP TRIGGER IF EXISTS log_rent_status_changes ON rental_system_rent;
            DROP TRIGGER IF EXISTS log_maintenance_status_changes ON rental_system_maintenance;
            DROP TRIGGER IF EXISTS log_maintenance_assignments ON rental_system_maintenance;

            CREATE TRIGGER log_equipment_changes
                AFTER INSERT OR UPDATE OR DELETE ON rental_system_equipment
                FOR EACH ROW EXECUTE FUNCTION log_table_changes();

            CREATE TRIGGER log_client_changes
                AFTER INSERT OR UPDATE OR DELETE ON rental_system_client
                FOR EACH ROW EXECUTE FUNCTION log_table_changes();

            CREATE TRIGGER log_rent_changes
                AFTER INSERT OR UPDATE OR DELETE ON rental_system_rent
                FOR EACH ROW EXECUTE FUNCTION log_table_changes();

            CREATE TRIGGER log_equipment_status_changes
                AFTER UPDATE ON rental_system_equipment
                FOR EACH ROW EXECUTE FUNCTION log_status_changes();

            CREATE TRIGGER log_rent_status_changes
                AFTER UPDATE ON rental_system_rent
                FOR EACH ROW EXECUTE FUNCTION log_status_changes();

            CREATE TRIGGER log_maintenance_status_changes
                AFTER UPDATE ON rental_system_maintenance
                FOR EACH ROW EXECUTE FUNCTION log_status_changes();

            CREATE TRIGGER log_maintenance_assignments
                AFTER UPDATE ON rental_system_maintenance
                FOR EACH ROW EXECUTE FUNCTION log_assignments();
            """,
            """
            DROP TRIGGER IF EXISTS log_equipment_changes ON rental_system_equipment;
            DROP TRIGGER IF EXISTS log_client_changes ON rental_system_client;
            DROP TRIGGER IF EXISTS log_rent_changes ON rental_system_rent;
            DROP TRIGGER IF EXISTS log_equipment_status_changes ON rental_system_equipment;
            DROP TRIGGER IF EXISTS log_rent_status_changes ON rental_system_rent;
            DROP TRIGGER IF EXISTS log_maintenance_status_changes ON rental_system_maintenance;
            DROP TRIGGER IF EXISTS log_maintenance_assignments ON rental_system_maintenance;
            """,
        ),
    ]

