# Generated by Django 5.2.7 on 2025-11-23
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental_system", "0016_recreate_log_triggers"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW equipment_return_debt_view AS
            SELECT
                cl.id AS client_id,
                cl.email,
                cl.phone_number,
                CASE
                    WHEN cl.type = 'individual' THEN
                        CONCAT(ind.last_name, ' ', ind.first_name,
                            CASE WHEN ind.patronymic IS NOT NULL THEN ' ' || ind.patronymic ELSE '' END)
                    WHEN cl.type = 'company' THEN comp.company_name
                    ELSE 'Неизвестный тип клиента'
                END AS client_name,
                cl.type AS client_type,
                r.id AS rent_id,
                r.rent_agreement_number,
                r.start_date,
                r.planned_end_date,
                COALESCE(r.actual_end_date, CURRENT_DATE) AS return_date,
                e.equipment_name,
                e.equipment_code,
                (CURRENT_DATE - r.planned_end_date) AS days_overdue,
                calculate_late_fee(r.id, 0.1) AS late_fee
            FROM rental_system_rent r
            JOIN rental_system_client cl ON r.client_id = cl.id
            JOIN rental_system_rentitems ri ON ri.rent_id = r.id
            JOIN rental_system_equipment e ON ri.equipment_id = e.id
            LEFT JOIN rental_system_indclient ind ON ind.client_id = cl.id AND cl.type = 'individual'
            LEFT JOIN rental_system_compclient comp ON comp.client_id = cl.id AND cl.type = 'company'
            WHERE r.actual_end_date IS NULL AND r.planned_end_date < CURRENT_DATE;
            """,
            """
            DROP VIEW IF EXISTS equipment_return_debt_view;
            """,
        ),
    ]

