# Generated by Django 5.2.7 on 2025-12-01
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental_system", "0017_fix_log_status_changes_dynamic"),
        ("rental_system", "0017_update_equipment_debt_view_with_penalty"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Универсальная функция логирования смены статусов (status или rent_status)
            CREATE OR REPLACE FUNCTION log_status_changes()
            RETURNS TRIGGER AS $$
            DECLARE
                old_status TEXT;
                new_status TEXT;
            BEGIN
                old_status := to_jsonb(OLD)->>'status';
                new_status := to_jsonb(NEW)->>'status';

                IF old_status IS NULL AND new_status IS NULL THEN
                    old_status := to_jsonb(OLD)->>'rent_status';
                    new_status := to_jsonb(NEW)->>'rent_status';
                END IF;

                IF (old_status IS DISTINCT FROM new_status) THEN
                    INSERT INTO rental_system_log(
                        log_date,
                        action_type,
                        description_text,
                        success_status
                    ) VALUES (
                        CURRENT_TIMESTAMP,
                        'CHANGE_STATUS',
                        CONCAT(
                            'Изменен статус в таблице ', TG_TABLE_NAME,
                            '. ID: ', OLD.id::TEXT,
                            '. Статус: ', COALESCE(old_status, 'NULL'),
                            ' → ', COALESCE(new_status, 'NULL')
                        ),
                        TRUE
                    );
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS log_status_changes() CASCADE;",
        ),
    ]
